name: Run ThreadSanitizer

on:
  push:

jobs:
  run-tsan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: c05e6a85d0b4c3ce249edc7748bde030fffc7209

      - name: Install dependencies for project (Linux)
        if: runner.os == 'Linux'
        run: | 
          sudo apt-get update && sudo apt-get install -y ninja-build meson
          
      - name: Build repository 
        run: | 
          export CC=clang
          export CXX=clang++
          export CFLAGS="-fsanitize=thread -fPIE -O2 -g -gcolumn-info"
          export LDFLAGS="-fsanitize=thread -pie"
          meson build
          cd build && ninja

      - name: Install ThreadSanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Thread Sanitizer (executables) (Linux)
        if: runner.os == 'Linux'
        run: |
            #!/bin/bash
            set +e
            DIRECTORY=$(pwd)
            
            is_executable() {
              local file="$1"
              if file "$file" | grep -q 'ELF 64-bit'; then
                return 0
              else
                return 1
              fi
            }
            
            run_with_tsan() {
              local executable="$1"
              TSAN_OPTIONS="force_seq_cst_atomics=1 exitcode=1 verbosity=2" timeout 10s "$executable"
              local exit_status=$?
            }
                          
            find "$DIRECTORY" -type f -executable | while read -r file; do
              if is_executable "$file"; then
                run_with_tsan "$file"
              fi
            done
